amazon-contributing/redis-rs

redis/src/cluster_routing.rs
redis/src/commands/mod.rs
redis/tests/test_cluster.rs
redis/tests/test_cluster_async.rs

The choices were based on the request_policy tip from the COMMAND output.

Update routing data for commands.

---

redis/src/cluster.rs
redis/src/cluster_async/mod.rs
redis/src/cluster_routing.rs

Moved build_slot_map to cluster.rs to be reused both by the async and sync cluster

Moved build_slot_map to cluster.rs

---

redis/src/cluster.rs
redis/src/cluster_async/mod.rs
redis/src/cluster_routing.rs
redis/src/cluster_topology.rs

Slot addresses should be filled with replicas, regardless of whether the cluster uses read_from_replica. This affects which nodes are queried during slot refresh, or AllNodes operations.

Move read_from_replica filtering to usage time.

---

redis/src/cluster.rs
redis/src/cluster_topology.rs

rebased over https://github.com/nihohit/redis-rs/pull/20

calculate_topology work with partial slot cover

---

redis/src/cluster_routing.rs

added the routing and response policy of : CONFIG SET, CONFIG RESETSTAT, CONFIG REWRITE.

Adding CONFIG commands to the request and response policy 

---

redis/src/cluster_routing.rs

Added ACL SETUSER, DELUSER to AllNodes & AllSucceed response and request policies

Added ACL SETUSER, DELUSER to AllNodes & AllSucceed policies

---

redis/src/cluster_async/mod.rs

- Changed create_initial_connections to raise the last received error on failure
This PR is a preparation for AUTH PR in python.

CME: Raise last received error in client init

---

redis/src/cluster_routing.rs
redis/src/commands/mod.rs

Also move the `is_readonly_cmd` function to the file where it's used.

Expose is_readonly command.

---

redis/src/cluster_routing.rs

Fix was accidently not merged with the rest of the PR.

Use random replica.

---

redis/src/cluster.rs
redis/src/cluster_async/mod.rs
redis/src/cluster_routing.rs
redis/tests/test_cluster_async.rs

That's the only scenario where it's needed.

Move response policy into multi-node routing.

---

.github/workflows/rust.yml

actions-rs is no longer maintained.

Update and use better maintained github actions.

---

redis/tests/test_cluster_async.rs

When refreshing slots we query all cluster nodes, so the test was fixed to check that each node was queried with a single CLUSTER NODES command, as we expect the refresh topology to be called once.

Fixed MOVED test

---

.github/workflows/rust.yml
redis/src/aio/connection.rs
redis/src/connection.rs

Update rust to version 1.65

---

redis/src/aio/multiplexed_connection.rs

This prevents reallocations / over allocations.

Allocate vec with exact required capacity.

---

redis/src/types.rs
redis/tests/test_types.rs

Fix debug names of values.

---

redis/src/cluster_client.rs

These were added in a copy-paste accident.

Remove unnecessary configuration limiters.

---

redis/src/cluster_routing.rs

These are used in the routing logic for standalone clients.

Expose Route getters.

---

redis/src/cluster_routing.rs

Expose more functions for standalonge routing.

---

redis/src/cmd.rs
redis/src/connection.rs
redis/src/macros.rs
redis/src/types.rs

It has been made redundant by the ? operator.

Remove the unwrap_or! macro.

---

.cargo/config.toml
redis/src/connection.rs

Renaming babushka to glide

---

redis/src/cluster_async/mod.rs

This PR removes the state duplication, where each request contains its original routing even after being redirected. Now the redirect and original routing are in the same field, and once a request has been redirected, the redirect overwrites the original routing.
https://github.com/aws/babushka/issues/695

Consolidate redirect and routing info.

---

redis/src/cluster_async/mod.rs

This PR cleans up the code in preparation for another PR which is in the works.
Doesn't cause any behavior change.

Code Cleanup

---

redis/src/commands/mod.rs
redis/src/streams.rs
redis/tests/support/mod.rs
redis/tests/support/sentinel.rs
redis/tests/test_cluster.rs
redis/tests/test_cluster_async.rs

Fix lints from new Rust version.

---

redis/src/cluster_async/connections_container.rs
redis/src/cluster_async/mod.rs

This PR serves as a base for utilizing management connections for topology queries.

Added connection management to the connections container

---

Cargo.toml
Makefile
redis/Cargo.toml
redis/src/aio/async_std.rs
redis/src/aio/connection_manager.rs
redis/src/aio/multiplexed_connection.rs
redis/src/aio/tokio.rs
redis/src/client.rs
redis/src/cluster.rs
redis/src/cluster_async/mod.rs
redis/src/cluster_client.rs
redis/src/cluster_routing.rs
redis/src/commands/mod.rs
redis/src/connection.rs
redis/src/tls.rs
redis/src/types.rs
redis/tests/support/cluster.rs
redis/tests/support/mock_cluster.rs
redis/tests/test_async.rs
redis/tests/test_basic.rs
redis/tests/test_cluster_async.rs
redis/tests/test_types.rs

Merge changes from upstream.

---

redis/tests/test_cluster.rs
redis/tests/test_cluster_async.rs

Remove unnecessary declared fields and usage of cluster builder. Most of these are just copied from test to test without considering whether they're needed.

Remove clutter from cluster tests. 

---

redis/src/cluster_async/connections_container.rs

The optional isn't used for any required functionality, and just complicates the code.

Remove the usage of Optional in connections map. 

---

Makefile
redis/Cargo.toml
redis/examples/async-await.rs
redis/examples/async-connection-loss.rs
redis/examples/async-pub-sub.rs
redis/examples/async-scan.rs
redis/src/aio/connection.rs
redis/src/aio/mod.rs
redis/src/aio/multiplexed_connection.rs
redis/src/client.rs
redis/src/cluster_pipeline.rs
redis/src/cmd.rs
redis/src/commands/json.rs
redis/src/connection.rs
redis/src/lib.rs
redis/src/pipeline.rs
redis/src/sentinel.rs
redis/src/types.rs
redis/tests/support/cluster.rs
redis/tests/support/mock_cluster.rs
redis/tests/support/mod.rs
redis/tests/test_async.rs
redis/tests/test_bignum.rs
redis/tests/test_cluster_async.rs
redis/tests/test_types.rs

Pull from upstream

---

Cargo.lock
Makefile

The lock file wasn't updated on the merge from upstream.

Update lock file.

---

redis/src/cmd.rs
redis/src/sentinel.rs
redis/tests/support/mod.rs
redis/tests/support/sentinel.rs
redis/tests/test_cluster_async.rs

Replace Vec reference with a slice, and remove iterator trait when using ExactSizeIterator, since it encompasses it.

Fix new clippy lints.

---

redis/src/cluster_async/connections_container.rs
redis/src/cluster_async/mod.rs
redis/tests/test_cluster_async.rs

https://github.com/aws/glide-for-redis/issues/741
Based on https://github.com/redis-rs/redis-rs/pull/968, which fixes issues in redis-rs.

Reset routing if redirect fails.

---

redis/src/cluster.rs
redis/src/cluster_async/mod.rs
redis/src/cluster_routing.rs
redis/tests/test_cluster_async.rs

https://github.com/aws/glide-for-redis/issues/483

Add support for routing by node address.

---

redis-test/src/lib.rs
redis/benches/bench_basic.rs
redis/examples/async-multiplexed.rs
redis/examples/basic.rs
redis/src/aio/connection_manager.rs
redis/src/cluster.rs
redis/src/cluster_async/connections_container.rs
redis/src/cluster_async/connections_logic.rs
redis/src/cluster_async/mod.rs
redis/src/cluster_routing.rs
redis/src/cluster_slotmap.rs
redis/src/cluster_topology.rs
redis/src/types.rs
redis/tests/test_async.rs
redis/tests/test_async_async_std.rs
redis/tests/test_cluster_async.rs
redis/tests/test_module_json.rs

https://github.com/amazon-contributing/redis-rs/actions/runs/7957250357/job/21719585654

Fix the nightly compile error.

---

redis/src/cluster_routing.rs

Added `base_routing` function that returns a simplified enum determining the way that a command should be routed. This can be called from any function that determines routing - `RoutingInfo::for_routable` or `RoutingInfo::is_all_nodes`.

Remove duplication in command routing.

---

.github/workflows/rust.yml
Makefile
redis-test/src/lib.rs
redis/Cargo.toml
redis/src/aio/connection.rs
redis/src/aio/connection_manager.rs
redis/src/aio/mod.rs
redis/src/aio/multiplexed_connection.rs
redis/src/client.rs
redis/src/cluster.rs
redis/src/cluster_client.rs
redis/src/cluster_routing.rs
redis/src/cmd.rs
redis/src/commands/mod.rs
redis/src/connection.rs
redis/src/lib.rs
redis/src/push_manager.rs
redis/src/script.rs
redis/src/types.rs
redis/tests/support/cluster.rs
redis/tests/support/mock_cluster.rs
redis/tests/support/mod.rs
redis/tests/test_async.rs
redis/tests/test_basic.rs
redis/tests/test_cluster.rs
redis/tests/test_cluster_async.rs
redis/tests/test_module_json.rs
redis/tests/test_types.rs

Merge push manager change from redis-rs.

---

Cargo.lock

https://github.com/advisories/GHSA-r8w9-5wcg-vfj7

Update mio dependency due to vulnerability.

---

redis/src/cluster_async/connections_container.rs
redis/src/cluster_async/mod.rs

The Identifier construct was a preparation for future optimization which is unlikely to manifest. As it is, it complicates the code unnecessarily, and so this PR removes it.

ConnectionsContainer: Remove identifier.

---

.github/dependabot.yml
.github/workflows/rust.yml
.gitignore
Cargo.lock
README.md
redis/CHANGELOG.md
redis/Cargo.toml
redis/src/aio/multiplexed_connection.rs
redis/src/client.rs
redis/src/parser.rs
redis/tests/support/mod.rs
redis/tests/test_async.rs
redis/tests/test_basic.rs
redis/tests/test_cluster.rs
redis/tests/test_cluster_async.rs
redis/tests/test_types.rs

Merge changes from upstream

---

redis/src/cluster_routing.rs

Added base routing for LOLWUT to a random node.

---

redis/src/client.rs
redis/src/cluster_client.rs
redis/src/cluster_routing.rs
redis/src/commands/json.rs
redis/src/commands/mod.rs
redis/src/streams.rs

Fix clippy warnings

---

redis/src/cluster_routing.rs

Add routing rules for `FUNCTION LIST`.

---

redis/src/cluster_routing.rs

N/A
Update list of RO commands according to redis docs.

Update list of RO commands.

---

redis/src/commands/cluster_scan.rs

added stream

---

redis/src/aio/connection.rs

Log fix: Log host and port when creating a new connection
