redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/src/parser.rs, redis/src/types.rs, redis/tests/test_cluster_async.rs
this PR is based over https://github.com/nihohit/redis-rs/pull/5.
This change implements the response_policy tip in the async cluster.
https://redis.io/docs/reference/command-tips/#response_policy
This means that the results from fan-out commands will be aggregated
differently, based on the sent command.
=> https://github.com/redis-rs/redis-rs/pull/888

.github/workflows/rust.yml, redis-test/Cargo.toml, redis/Cargo.toml, redis/src/geo.rs, redis/src/streams.rs, redis/tests/support/cluster.rs
It is now required that the cluster creation waits for all servers to change their state to OK before it returns, rather than waiting only for the first one to change its state.
This change prevents flaky tests due to CLUSTER DOWN errors by not starting testing before all servers are ready.
=> Changed cluster creation to wait for all servers to change their state to OK

redis/src/cluster.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/tests/test_cluster_async.rs
This allows the async cluster client to split keyed commands so that
keys will be grouped by the slot they belong in, and sent only to the
relevant shard.
=> Add support for multi-shard commands.

redis/src/connection.rs
Changed deprecated method rustls::RootCertStore::add_server_trust_anchors to add_trust_anchors
=> Changed deprecated rustls method

redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
This means multi node operations now get error handling, and can trigger MOVED, etc.
Additionally, `func` was removed from `CmdArg::Cmd/Pipeline`. This removes the need 
to allocate a box on every request, and reduces code complexity by eliminating an
unnecessary generic type.
=> Execute multi-node requests using try_request.

redis/src/cluster_topology.rs
read_from_replica isn't relevant there. It's only for reads.
=> AllNodes should always take replicas

redis/src/cluster.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/src/cluster_topology.rs
This reverts most of https://github.com/nihohit/redis-rs/pull/16, and instead uses the read_from_replica flag when finding the route for each command.
=> Pass read_from_replica flag when finding routing.

redis/src/cluster_routing.rs, redis/src/cluster_topology.rs
This change allows the SlotMap to return `None` when querying slots which are in the range between slots.
This wasn't possible before because the SlotMap only saved the end of each slot range, and assumed that the beginning of the range is the end of the previous range + 1.
Also moved the SlotMap test to the file that contains SlotMap.
=> SlotMap: Be able to handle holes in slots.

redis/src/aio/connection.rs, redis/src/cluster_async/mod.rs
Changed the cluster initialization to retrieve all IP entries from the initial nodes and use all resolved IPs.
=> Added to the initial_nodes list all retrieved IP entries

redis/tests/support/mock_cluster.rs
Fixes the implementation to behave correctly when the configuration contains more than a single replica per shard. Each replica should be in its own array, but all replica arrays were flattened into a single array.
=> create_topology_from_config: Use all replicas.

redis/src/cluster.rs, redis/src/cluster_topology.rs
`fill_slots` carried an implicit assumption that the `SlotMap` was cleared before the call, otherwise the resulting map contained some old and some new slots. This change ensures that slot replacement removes all old slots.
=> Fix SlotMap inconsistency.

redis/src/cluster_routing.rs
Removed CONFIG GET from AllNodes request policy and AllSucceeded response policy. CONFIG GET will be sent to a random node.
=> Changed CONFIG GET to be sent to a random node

redis/src/aio/connection.rs, redis/src/client.rs, redis/src/cluster_async/mod.rs, redis/tests/support/mock_cluster.rs, redis/tests/test_cluster_async.rs
This option doesn't break the user facing API.
Fixed the initial nodes expander to return the socketAddr object and maintain the provided hostname, for TLS hostname verifications.
The Subject Alternative Name (SAN) is an extension to the X.509 specification that allows users to specify additional host names for a single SSL certificate. In ElastiCache cluster TLS certificate there is a subject name containing the suffix of the cluster name, e.g.: *.barshaul-babushka-standalone-test-tls.ez432c.use1.cache.amazonaws.com. When we expand the DNS endpoint to multiple node addresses, we shall save the provided hostname in order to be able to verify the node with the TLS cert.
=> Fixed the initial nodes expander - option #2

.github/workflows/rust.yml
We see some tests failing due to timeouts after 35 minutes.
=> Increase timeouts and use newer redis.

redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs
Added connections_manager, a single object that handles addition, removal, and fetching of connections. This will allow us to easily modify behavior, for example, by adding round-robin read from replica.
=> Wrap cluster connection management in object.

redis/src/aio/connection.rs, redis/src/client.rs, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/tests/support/mock_cluster.rs, redis/tests/test_cluster_async.rs
Before reusing an old connection, check if its node has encountered a DNS change, where the node's endpoint now leads to a different IP address.
Implementation detailes:
connect_simple now returns both the connection and an optional String with the connection IP (only valid for TCP connections, for Unix returns None). 
The cluster client now holds a ConnectionMap from the node's name to ClusterNode entries that holds both the connection and the IP. When we check if existing connection is valid in the get_or_create_conn function, we now also check if the node's address still points to the same IP.
=> Added a check for DNS updates

Makefile
Apparently there's some hidden race condition between the tests. Locally
this prevented crashes.
=> Run module tests sequentially. 

redis/tests/support/cluster.rs
This might help us understand the flakyness in the cluster tests.
=> Log cluster creation output in tests.

redis/Cargo.toml, redis/src/cluster_async/mod.rs, redis/src/cluster_topology.rs, redis/tests/test_cluster_async.rs
This will allow us to handle the traces with logger_core.
=> Use the tracing crate instead of the log crate.

redis/src/cluster_routing.rs
Re-adds commands that was removed by mistake in this PR: https://github.com/nihohit/redis-rs/pull/43
=> Re-adds removed commands from AllSucceed response policy

redis/src/cluster.rs, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_client.rs, redis/src/cluster_routing.rs, redis/src/cluster_topology.rs, redis/tests/test_cluster_async.rs
based over https://github.com/nihohit/redis-rs/pull/22 and https://github.com/nihohit/redis-rs/pull/23 .
=> Implement round robin read from replica strategy for async cluster.

redis/Cargo.toml, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs
This reduces the cost of identifier clones from O(n) to O(1), reduces the size of the Identifier to usize, and reduces the number of allocations.
=> Minor optimization: Use ArcStr as node identifier.

redis/Cargo.toml, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_client.rs, redis/src/cluster_topology.rs, redis/tests/test_cluster_async.rs
This PR adds an optional periodic topology checks to the async cluster client. 
The current periodic check use the user's connections. On the next PR I will add management connections that will be used for this checks. 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/barshaul/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/barshaul/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style> …
=> Added periodic topology checks

redis/src/commands/mod.rs, redis/src/connection.rs, redis/src/streams.rs, redis/tests/test_streams.rs
Fix XREADGROUP command ordering as per Redis Docs, and compatibility with Upstash Redis (#960)
=> Fix linter, cherry pick from upstream

redis/src/cluster_async/mod.rs, redis/src/commands/mod.rs, redis/src/streams.rs, redis/tests/test_streams.rs
Fixed the initial connection map in the cluster to use the direct IP address when available as a key, rather than using the DNS entry.
Rebased over #58
=> Fixed the initial connection map 

redis/src/cluster_async/mod.rs
Temp fix: Change 'addresses to connections' (specifically get_socket_addrs) to be sequential instead of concurrent in order to workaround DNS query throttling
=> refresh_slots fix dns resolve delay

redis/src/cluster_async/mod.rs
This change will cause transactions with commands that are routed to replicas and primaries to prefer the primary routing over the replica.
=> Prefer routing to primary in a transaction.

redis/src/aio/multiplexed_connection.rs
Instead of using a Vec<Value> and allocating / popping values from it,
single requests will now create only a single Value object, which will
reduce the heap usage for single requests.
This gives us a small but consistent perf improvement of about 1% for Node benchmarks, and ~5% for Rust benchmarks.
=> MultiplexedConnection: Remove unnecessary allocation in send.

redis/src/cluster.rs, redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
=> Use `Value::Map` to aggregate cluster responses.

redis/src/cluster.rs, redis/src/cluster_client.rs, redis/tests/support/cluster.rs, redis/tests/support/mod.rs, redis/tests/test_cluster.rs, redis/tests/test_cluster_async.rs
=> Add RESP3 support to cluster connections.

redis/src/cluster_routing.rs
Instead of allocating the ASCII uppercase conversion of `self.arg_idx(1)` and then copying it into the target vec, we copy the slice, and then convert it to uppercase in-place. This saves the allocation of the vec, which is only used for copying.
The perf difference here is too small to be conclusive in benchmarks, but the reduction in the generated assembly is noticable (~920 lines of assembly to ~800) - https://godbolt.org/z/7srEv8vra
=> Remove allocation from `command` function.

redis/Cargo.toml, redis/src/aio/mod.rs, redis/src/cluster.rs, redis/src/cluster_client.rs, redis/src/connection.rs, redis/src/sentinel.rs, redis/tests/support/cluster.rs, redis/tests/support/mod.rs, redis/tests/support/util.rs, redis/tests/test_async.rs, redis/tests/test_basic.rs, redis/tests/test_cluster.rs, redis/tests/test_cluster_async.rs
Part of https://github.com/aws/babushka/issues/407
Add optional client_name property to RedisConnectionInfo, which will be used with 'CLIENT SETNAME' command during connection setup.
=> Add support for client name configuration

redis/src/cluster.rs, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/src/cluster_topology.rs
If the `SlotMap` is partial, and some slots don't have addresses, then we need to communicate this back when getting addresses for multi-slot commands. Otherwise we the key indices won't match the addresses, and commands with the wrong keys will be sent to the wrong nodes.
=> Fix multi-slot routes/addresses mismatch.

Makefile, redis/src/aio/connection.rs, redis/src/aio/mod.rs, redis/src/cluster.rs, redis/src/cluster_client.rs, redis/src/connection.rs, redis/src/lib.rs, redis/src/sentinel.rs, redis/src/types.rs, redis/tests/support/cluster.rs, redis/tests/support/mod.rs, redis/tests/test_async.rs, redis/tests/test_basic.rs, redis/tests/test_cluster.rs, redis/tests/test_cluster_async.rs
Since there's a discussion starting about what might become RESP4, this PR will make it easier to add more RESP versions in the future.
=> Use enum instead of boolean for RESP version.

redis/src/cluster_async/mod.rs
These TODOs can't be solved without a significant refactor, since the reference can't be saved for async operations without owning the value. If there will be such a refactor, it won't be because of these comments.
=> Remove unnecessary todos.

Makefile, redis/tests/support/mod.rs, redis/tests/test_async.rs, redis/tests/test_async_async_std.rs, redis/tests/test_cluster_async.rs
ATM Tokio's runtimes hide panics from spawned tasks, and continue running. This PR ensures that we'll be catch panics even if they're thrown in spawned tasks.
=> Catch panics from task::spawn in tests.

redis/src/cluster_topology.rs
Increased default refresh slots retry interval to reduce chances for connection storms.
Related issue: https://github.com/aws/babushka/issues/532
=> Increased default refresh slots retry interval

redis/tests/support/mock_cluster.rs
Extended MockConnection utilities to have differed returned IPs and to return connection errors
This PR is a base for the management connection tests PR.
=> Extended MockConnection utilities 

redis/src/cluster_async/mod.rs, redis/src/types.rs, redis/tests/support/mod.rs, redis/tests/test_cluster_async.rs
https://github.com/aws/babushka/issues/733
=> Handle missing connections without panicking.

redis/src/cluster.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/src/cluster_topology.rs, redis/src/types.rs, redis/tests/test_cluster.rs, redis/tests/test_cluster_async.rs
https://github.com/aws/babushka/issues/659
https://github.com/aws/babushka/issues/532
https://github.com/aws/babushka/issues/430
based over https://github.com/amazon-contributing/redis-rs/pull/95
1. When parsing slots, now the slots will be sorted, to ensure that they're ordered the same way regardless of the order returned from the server.
2. When parsing slots, if hostname is missing, fill it in with the queried node's hostname.
3. Hash the topology view according to the parsed slots instead of the returned values, in order to account for the 2 fixes in the hash.
=> Fix issues with slot parsing in cluster connections.

redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
https://github.com/aws/glide-for-redis/issues/791
After the async cluster receives a `ConnectionNotFound` error, it means
that the cluster has no working connections, and can't refresh slots. In
such a situation the cluster will try to reconnect to the initial nodes
provided by the user, and afterwards refresh slots.
=> Async cluster: reconnect after full disconnect.

redis/Cargo.toml, redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_client.rs, redis/src/lib.rs, redis/tests/support/mock_cluster.rs, redis/tests/test_async_cluster_connections_logic.rs
This moves the free connection functions from the async cluster to a separate file, and add tests to this file.
=> Create connections logic file.

redis/src/cluster_topology.rs, redis/tests/support/mock_cluster.rs, redis/tests/test_cluster.rs, redis/tests/test_cluster_async.rs
Based on the description of CLUSTER SLOTS (https://redis.io/commands/cluster-slots/):
> The preferred endpoint, along with the port, defines the location that clients should use to send requests for a given slot. A NULL value for the endpoint indicates the node has an unknown endpoint and the client should connect to the same endpoint it used to send the CLUSTER SLOTS command but with the port returned from the command. This unknown endpoint configuration is useful when the Redis nodes are behind a load balancer that Redis doesn't know the endpoint of. Which endpoint is set as preferred is determined by the cluster-preferred-endpoint-type config. An empty string "" is another abnormal value of the endpoint field, as well as for the ip field, which is returned if the node doesn't know its …
=> Added handling to "?" and NULL hostnames in CLUSTER SLOTS

redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/tests/support/mock_cluster.rs, redis/tests/test_async_cluster_connections_logic.rs, redis/tests/test_cluster_async.rs
=> Add `check_node_connections` function.

redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/src/lib.rs, redis/tests/test_async_cluster_connections_logic.rs
These types will now be under a `testing` module, thus communicating that they shouldn't be used externally.
=> Reduce visibility of types that are used only for testing.

redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/tests/test_async_cluster_connections_logic.rs
=> connect_and_check: Allow choosing which connections to refresh.

redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
Async cluster connection will now use additional, management connections in order to get topology refreshes.
=> Use management connections in topology refresh.

redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
Loading errors on primary should retry, and on replica should remove the replica & retry.
https://github.com/aws/glide-for-redis/issues/324
=> Handle loading errors.

redis/src/cluster_routing.rs, redis/src/cluster_topology.rs
Fixed the parsing of cluster slots to sort the replicas in each view to ensure accurate view comparisons based on hash.
Removed sorting of the slots order as Redis's implementation for CLUSTER SLOTS is being done by iterating through (0...16383) and therefore creating the returned slots map already in order. The only issue is that different nodes can hold a different order of the replicas in their view and this isn't being ordered in the server side.
Closes https://github.com/aws/glide-for-redis/issues/933
=> Fixed the parsing of cluster slots to sort the replicas in each view

redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs
Commands which have more arguments that aren't keys shouldn't be routed according to the hash of the additional arguments.
=> Route unkeyed commands to a random node.

redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
This change will ensure that failing management connections that were found in the periodic check will be reconnected automatically.
=> Reconnect failing management connections.

Cargo.lock, redis/Cargo.toml, redis/src/parser.rs, redis/src/types.rs, redis/tests/parser.rs
`ordered_float` was needed in order to derive the `Eq` trait, which is no longer in use. This allows us to align our code with redis-rs.
=> Remove ordered_float from `Value`.

redis/src/parser.rs, redis/src/types.rs
Parsing errors are client-side errors, that are caused by bad output from the server. Response errors are server-side errors, caused by bad input from the user / client. Parse errors cause the client to be in an unrecoverable state. response errors are OK.
=> Separate parsing errors from general response errors.

Cargo.lock, Makefile, README.md, redis-test/CHANGELOG.md, redis-test/Cargo.toml, redis/CHANGELOG.md, redis/Cargo.toml, redis/examples/async-multiplexed.rs, redis/src/aio/connection_manager.rs, redis/src/aio/mod.rs, redis/src/aio/multiplexed_connection.rs, redis/src/aio/runtime.rs, redis/src/client.rs, redis/src/cluster.rs, redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_client.rs, redis/src/cluster_routing.rs, redis/src/connection.rs, redis/src/parser.rs, redis/src/types.rs, redis/tests/support/cluster.rs, redis/tests/support/mod.rs, redis/tests/test_async.rs, redis/tests/test_async_async_std.rs, redis/tests/test_basic.rs, redis/tests/test_cluster.rs, redis/tests/test_cluster_async.rs
Pull recent changes to https://github.com/redis-rs/redis-rs.
=> Merge from upstream

redis/src/cluster_routing.rs
This function will be used to verify that multi node routing isn't used with key-based command. 
This scenario is possible when the user is using custom command.
The `match` ensures that if a new RouteBy type will be added the compiler will enforce adding it to this function as well
=> Added a public function to check if a command is key-based 

redis/src/cmd.rs
In order to easily print command arguments to error logs
=> Implement Debug trait for Cmd

redis/src/cluster_routing.rs
N/A
This change fixes cluster routing for the OBJECT FREQ command. Without this change, integration tests for OBJECT FREQ fail in glide-for-redis .
=> Fix cluster routing for OBJECT FREQ command

redis/src/aio/tokio.rs
We've encountered situations where the server's host fails to respond with an ACK to a transmitted message, causing the connection to hang on send_recv. To resolve this issue, we've implemented the socket2 set_tcp_user_timeout function. 
Currently, this PR introduces a hardcoded timeout value of 5 seconds. However, in the future, when we have more resources, we plan to make it a configurable variable. You can find more information at https://github.com/redis-rs/redis-rs/issues/1147.
=> Added hardcoded user TCP timeout

redis/Cargo.toml, redis/src/aio/tokio.rs
1. Adjusted socket2 features to address analyzer error. 
2. TCP User Timeout: Introduced target_os configuration, recognizing that this feature lacks support across all operating systems.
3.
=> Fix TCP_USER_TIMEOUT compatibility with different OS and analyzer

redis/src/cluster_routing.rs, scripts/get_command_info.py
N/A
- Adds a script that analyzes json info from the [valkey commands directory](https://github.com/valkey-io/valkey/tree/26388270f197bce84817eea0a73d687d58442654/src/commands) and categorizes commands based on their RouteBy mapping
- Updates cluster_routing.rs#base_routing with the info obtained from the script
- Includes adding a RouteBy::SecondArgAfterKeyCount mapping
- Changes some incorrect mappings based on the script output
- WAITAOF was mapped to Random but is now mapped to AllPrimaries
- BITOP was mapped to Undefined but is now mapped to SecondArg
- MOVE was mapped to Undefined but is now mapped to FirstKey
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> Added script to gather command info and updated base_routing

redis/src/cluster_routing.rs
`WATCH` and `UNWATCH` works on cluster client only if `UNWATCH` was accidentally routed to the same node where key is located.
Running this test fails on the last assert as it mostly returns null because `UNWATCH` doesn't hit the right node.
```
String key = "a";
ClusterTransaction testTrans = new ClusterTransaction();
clusterClient.set(key, "init").get();
clusterClient.watch(new String[] {key}).get();
clusterClient.customCommand(new String[] {"unwatch"},
SimpleSingleNodeRoute.RANDOM).get();
clusterClient.set(key, "racecondition").get();
testTrans.set(key, "doesthiswork");
assertArrayEquals(new String[] {OK}, clusterClient.exec(testTrans).get());
assertEquals("doesthiswork", clusterClient.get(key).get()); // Returns null 
```
By …
=> Added UNWATCH to AllPrimaries routing

redis/Cargo.toml
The url crate has been upgraded to 2.5.1, and it includes the Unicode-3.0 license which is not accepted by rust-lint.
This is now failing on gilde's CI main: https://github.com/aws/glide-for-redis/actions/runs/9452141168/job/26034681086
```
error[rejected]: failed to satisfy license requirements
┌─ registry+https://github.com/rust-lang/crates.io-index#icu_properties@1.5.0:4:12
│
4 │ license = "Unicode-3.0"
│            ^^^^^^^^^^^
│            │
│            license expression retrieved via Cargo.toml `license`
│            rejected: not explicitly allowed
│
= Unicode-3.0 - Unicode License v3:
=   - OSI approved
= icu_properties v1.5.0
├── icu_normalizer v1.5.0
│   └── idna v1.0.0
│       └── url v2.5.1
│           └── redis v0.25.2
│               ├── glide-core v0.1.0
│               │ …
```
=> Changed the 'url' package version to be fixed to v2.5.0 to enforce license requirements

redis/src/cluster_routing.rs
This change is required to support clients to receive one `OK` response for request to clusters. This will make these requests more consistent to commands like `PING`. Related and builds on changes from https://github.com/amazon-contributing/redis-rs/pull/152 
=> Added support for aggregating responses for WATCH and UNWATCH

redis/src/connection.rs
Fix pubsub doc url to point to valkey
=> Fix pubsub doc url to point to valkey

.github/workflows/rust.yml, Cargo.lock, Makefile, redis/Cargo.toml, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_slotmap.rs, redis/src/commands/cluster_scan.rs, redis/src/commands/mod.rs, redis/src/lib.rs, redis/src/types.rs, redis/tests/support/cluster.rs, redis/tests/support/mod.rs, redis/tests/test_cluster_scan.rs
This PR contains the implementation of scanning a Redis cluster.
Replacing the `cursor` the user use to interact with the SCAN process by a state cursor representing the state of the scan base on the internal logic implemented.
The general idea is behind the scene to scan node by node and track the progress and changes of the cluster topology affects the scan and adjust the scan accordingly, while still keep the promises of the scan operation, such as returning all keys were in the cluster from beginning to end or keep the operation "stateless", do it efficiently, and give the user the touch and feel of a standalone server.
1. `cursor` - The real cursor is used to scan the current node.
2. `scanned_slots_map` - a 16384 bits array, represent the progress of the scan, in which slots that …
=> Add cluster scan functionality

redis/src/cluster_async/mod.rs, redis/src/commands/cluster_scan.rs, redis/tests/test_cluster_scan.rs
Changed checks from refreshing slots on each node to periodic check on each node
This change decreases the time the scan on a cluster of 150 nodes, 100000 keys, 1000 sets and 1000 hashes to 200ms, while without any check it's taking 100ms.
=> Changed checks from refreshing slots on each node to periodic check on each node

redis/src/cluster.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/tests/support/mock_cluster.rs, redis/tests/test_cluster_async.rs
Attempt to return the first result that isn't `Nil` or an error.
If no such response is found and all servers returned `Nil`, it indicates that all shards are empty, so return `Nil`.
If we received only errors, return the last received error.
If we received a mix of errors and `Nil`s, we can't determine if all shards are empty, thus we return the last received error instead of `Nil`.
=> Async cluster: Changed OneSucceededNonEmpty to FirstSucceededNonEmptyOrAllEmpty

redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
Including:
1. Handle errors even when out of retries. - https://github.com/redis-rs/redis-rs/pull/1186
2. Send retries in multi-node reconnect to new connection https://github.com/redis-rs/redis-rs/pull/1202
=> Merge fixes from upstream

redis/src/cluster_async/mod.rs, redis/src/cluster_client.rs, redis/src/cluster_topology.rs, redis/src/commands/cluster_scan.rs, redis/tests/test_cluster_async.rs, redis/tests/test_cluster_scan.rs
Rebased over #165
This PR introduces a rate limiter to the slots refresh operations, enhancing the efficiency and stability of the system. Consecutive request calls will no longer trigger slot refresh too often, as this is an expensive operation. Note that even when slot refresh is skipped, requests that receive MOVED errors will be immediately routed to the redirect node.
Additionally, this PR adds a new configuration option for the async cluster client: `slots_refresh_rate_limit`. This configuration allows the user to set the wait duration and jitter for rate limiting slot refresh operations, providing greater control over the refresh behavior.
This PR disables the rate limiter for tests that require immediate slot refresh after client creation.
=> Added a rate limiter to the slots refresh operations

redis/src/aio/connection.rs, redis/src/cluster_async/mod.rs
Change error caught internally to be logged as warnings and added dedicated message to explain to the user that the error is being handled internally. Added a log of the host IP when a new connection is being created.
It's important so we'll be able to help debugging issues for users later on.
=> Improved client logs

redis/src/cluster_async/mod.rs
Reducing the number of max requested nodes in order to be "on the safe side" and reducing the load in large clusters where the CLUSTER SLOTS response can get large.
=> Reduced the max number of queried nodes in topology request

redis/src/cluster_async/mod.rs
ATM refresh connections is being called from each periodic check even when no failed connections were found which resulting in a lot of logs like:
```
[2m2024-07-03T17:07:12.769490Z[0m [32m INFO[0m [2mredis::cluster_async[0m[2m:[0m Started refreshing connections to []
[2m2024-07-03T17:07:12.769523Z[0m [32m INFO[0m [2mredis::cluster_async[0m[2m:[0m refresh connections completed
[2m2024-07-03T17:07:14.331242Z[0m [32m INFO[0m [2mredis::cluster_async[0m[2m:[0m Started refreshing connections to []
[2m2024-07-03T17:07:14.331271Z[0m [32m INFO[0m [2mredis::cluster_async[0m[2m:[0m refresh connections completed
[2m2024-07-03T17:08:12.771693Z[0m [32m INFO[0m [2mredis::cluster_async[0m[2m:[0m Started refreshing connections to [] …
```
=> Call to refresh_connections only if failed_conn isn't empty

redis/src/cluster_async/mod.rs
[closing client does not terminate redis-rs 1787](https://github.com/aws/glide-for-redis/issues/1787)
Changing client closing logic - instead of marking with flag and closing in topology check, holding handler and closing immidietlly. 
=> fixed close connection logic

redis/src/cluster_async/mod.rs, redis/src/commands/cluster_scan.rs, redis/tests/test_cluster_scan.rs
=> Add binary support

redis/src/aio/connection.rs
This bug affects clusters in non-TLS setups that use a DNS endpoint storing multiple addresses, such as the cluster discovery endpoint in ElastiCache/MemoryDB.
When expanding a DNS endpoint from the initial nodes, we store the `socket_address` received from the expansion. However, in non-TCP connections, we haven't used the received `socket_address`. Instead, we re-resolved the original DNS entry when creating the actual connection. This caused a faulty mapping between the node address and the actual connection.
Consider the endpoint `cluster.dns.endpoint` expanded to IP1, IP2, and IP3. Previously, all nodes were mapped to a connection with the first address resolved from `cluster.dns.endpoint`. If a DNS lookup for `cluster.dns.endpoint` returns the order [IP1, IP2, IP3], the connection …
=> Critical bug fix: Fix cluster-mode TLS disabled client to properly take received IPs when DNS is expanded

redis/tests/test_cluster_async.rs
=> added blocking commands tests

redis/src/cluster_async/mod.rs, redis/tests/test_cluster_async.rs
Fixed non key based commands not to be routed to a random node when specific route is provided and connection isn't found.
=> Fixed non key based commands not to be routed to a random node 

redis/src/aio/connection.rs, redis/src/client.rs, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_client.rs, redis/src/cluster_topology.rs, redis/tests/support/cluster.rs, redis/tests/support/mod.rs, redis/tests/test_async_cluster_connections_logic.rs, redis/tests/test_basic.rs, redis/tests/test_types.rs
The main purpose of this PR is to allow having connections with different IPs to the same node.
This PR contains three commits:
- Improve logging
- Removed IP checks from the connection logic: On different managed services the given endpoints are actually load balancers and the same DNS entry of a "node" might be routed to different IPs of different LBs. That means that we shouldn't fail the creation of management connection on "mismatched IPs" found between the user and the management connection. 
- Refactored each node connection to be stored with its own IP address. We now use the `ConnectionWithIp` type, which wraps both the actual connection and its associated IP address.
=> Allow having connections with different IPs to the same node

redis/src/cluster.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs
=> Handle PubSub commands routing

.github/workflows/rust.yml, redis/tests/support/mod.rs
1.  CI: Updated the CI configuration to execute on pull requests opened against all branches, enabling development on feature branches.
2. Removed the test_block_on_all_panics_from_spawns test as we currently didn't pull the workaround to fix it
=> CI: Updated the CI configuration to execute on pull requests opened all branches

redis/src/cluster_async/mod.rs, redis/src/commands/cluster_scan.rs
Refined slot refresh logic to accept RedirectNode, enabling targeted updates driven by moved redirects.
This commit lays the groundwork without yet implementing the actual slots map updates.
=> Added moved_redirect to the refresh slots function

Cargo.lock, redis/Cargo.toml, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs
This PR changes the connection map data structure to DashMap, which helps reduce write lock contention on the connection container. The write lock on the connection container now will only be used when both slots and connection maps are being replaced.
=> Refactored the connections map from HashMap to DashMap

redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs
This change ensures that SPUBLISH messages won’t be redirected to a random node if the intended target node isn’t available. The optimization of routing to a random node should only apply to commands that return a MOVED error if the target node isn’t the slot owner. The issue with SPUBLISH is that its behavior is unpredictable when redirected: if the randomly chosen node is outside the slot’s shard, a MOVED error will be returned; otherwise, the command might succeed, leading to inconsistent behavior. To address this, we will implement a PRIMARY_PREFERRED routing strategy for SPUBLISH, deliberately routing failed SPUBLISH commands to other nodes within the same shard.
=> Handle SPUBLISH as a non key-based command

redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/src/commands/cluster_scan.rs, redis/src/types.rs, redis/tests/test_cluster_async.rs, redis/tests/test_cluster_scan.rs
1. Breaking changes: The `ClusterConnectionNotFound` error has been renamed to `AllConnectionsUnavailable`, and a new error, `ConnectionNotFoundForRoute`, has been introduced to handle cases where a specific connection cannot be found. Previously, `ClusterConnectionNotFound` was incorrectly used for missing specific connections, which triggered `reconnect_to_initial_nodes`. However, `reconnect_to_initial_nodes` should only be invoked when all connections are unavailable, as its purpose is to gather more information from the seed nodes. With this update, when `ConnectionNotFoundForRoute` is encountered, the system will call `refresh_slots` and retry the request according to the configured retry logic.
2. Although `reconnect_to_initial_nodes` is now intended to be called only when no …
=> Breaking change: reconnect_to_initial_nodes will be called only when AllConnectionsUnavailable 

redis/src/cluster.rs, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/src/cluster_slotmap.rs, redis/src/cluster_topology.rs, redis/src/commands/cluster_scan.rs
This PR lays the foundation for supporting topology changes triggered by MOVED errors.
Slot Map Design
Currently, our slot map contains only a tree structure representing the slots and their associated ShardAddr, which holds the primary and replica addresses. For non-consecutive slots owned by the same shard, a new ShardAddr is created. The proposed design introduces the following enhancements:
1. Addition of a NodesMap: This map will store node identifiers (host:port) as keys, with their corresponding ShardAddrs as values. This allows primary and replicas of the same shard to share the same ShardAddr, reducing redundancy.
2. Read/Write Lock on ShardAddr: The ShardAddr will be wrapped in a read/write lock. The write lock will only be used when changes to the shard addresses are necessary …
=> SlotMap refactor: Added NodesMap, sharing shard addresses between shard nodes and slot map values.

redis-test/src/lib.rs, redis/examples/async-await.rs, redis/examples/async-connection-loss.rs, redis/examples/async-multiplexed.rs, redis/examples/async-pub-sub.rs, redis/examples/async-scan.rs, redis/src/aio/connection.rs, redis/src/aio/connection_manager.rs, redis/src/aio/mod.rs, redis/src/aio/multiplexed_connection.rs, redis/src/client.rs, redis/src/cluster_async/connections_logic.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_client.rs, redis/src/lib.rs, redis/src/sentinel.rs, redis/tests/support/mock_cluster.rs, redis/tests/support/mod.rs, redis/tests/test_async.rs, redis/tests/test_async_async_std.rs, redis/tests/test_async_cluster_connections_logic.rs, redis/tests/test_cluster_async.rs, redis/tests/test_sentinel.rs
Introduce a fast reconnect process for async cluster connections.
The process is periodic and can be configured via ClusterParams.
This process ensures that all expected user connections exist and have not been passively closed.
The expected connections are calculated from the current slot map.
Additionally, for the Tokio runtime, an instant disconnect notification is available, allowing the reconnect process to be triggered instantly without waiting for the periodic check.
This process is especially important for pub/sub support, as passive disconnects can render a pub/sub subscriber inoperative. Three integration tests are introduced with this feature: a generic fast reconnect test, pub/sub resilience to passive disconnects, and pub/sub resilience to scale-out.
**Note!** This PR must be …
=> Introduce a fast reconnect process for async cluster connections.

redis/benches/bench_basic.rs, redis/benches/bench_cluster_async.rs, redis/src/cluster_async/mod.rs, redis/tests/support/mod.rs, redis/tests/test_cluster_async.rs
https://github.com/valkey-io/valkey-glide/issues/2138
=> Do not retry requests that have been dropped by the user.

redis/benches/bench_basic.rs, redis/benches/bench_cluster_async.rs, redis/src/cluster_async/connections_container.rs, redis/src/cluster_async/mod.rs, redis/src/cluster_routing.rs, redis/src/cluster_slotmap.rs, redis/src/cluster_topology.rs, redis/tests/support/mod.rs, redis/tests/test_cluster_async.rs
Added logic to update the slot map based on MOVED errors. Now, when a MOVED error is received, the client will push a new future before retrying the request to attempt to update the slot map based on the new primary node, while still spawning a background task to refresh slots. This provides an optimization to ensure quicker rerouting of requests without waiting for the background slot refresh which can be skipped due to the rate limiter.
The updated logic handles several scenarios:
1. **No Change**: If the new primary is already the current slot owner, no changes are required.
2. **Failover**: If the new primary is a replica in the same shard, the client promotes the replica to primary by updating the shard's addresses.
3. **Slot Migration**: If the new primary is the existing primary of …
=> Added logic to update the slot map based on MOVED errors

redis/src/aio/tokio.rs, redis/src/cluster_routing.rs
This fixes a regression introduced by commit: 41de670
The change in the mentioned commit forces a routing to a random, but primary node in case the command is a "@write" command. Although the above commit is correct, it causes too much integration tests breakage in the consuming package (i.e. valkey-glide)
So I am reverting the forced behavior of Random primary
=> Don't force the RandomPrimary logic

redis/src/cluster_async/mod.rs
- **Lock Management Improvement**:
In the previous implementation, the read lock (`inner.conn_lock.read()`) was held throughout the entire connection refresh process (for all connections sent to refresh), including while attempting to establish connections (via `get_or_create_conn`). If connections were slow or timed out, the lock was held for an extended duration, blocking other tasks requiring a write lock.
The new implementation releases the read lock **before** making connection attempts. If the connection is successfully established, the read lock is reacquired to update the connection container. This approach ensures that other operations needing the lock (e.g., write operations) can proceed while connections are being established.
- **Unclear Deadlock Behavior**:
A deadlock …
=> Release the read lock while creating connections in`refresh_connections` 
